name: continuous integration
on:
  push:
    branches: [ "**" ]
jobs:
  test_codebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.14
      - name: Install pip
        run: python3 -m pip install --upgrade pip
      - name: Install pytest
        run: pip install -r requirements.txt
      - name: Run pytest
        run: pytest